### ISSUE TITLE
Syntax error at offset X near Y when query contains dash '-'

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#108]
Hi @slorello89.  Hope all is going well with your busy work.

I ran into an issue where I'm trying to query by exact match and my query has a dash `-` in it.  
Hopefully this is an easy fix?

```csharp
StackExchange.Redis.RedisServerException : Syntax error at offset 25 near accountant
   at Redis.OM.RedisConnection.ExecuteAsync(String command, String[] args)
   at Redis.OM.RediSearchCommands.SearchAsync[T](IRedisConnection connection, RedisQuery query)
   at Redis.OM.Searching.RedisCollectionEnumerator`1.GetNextChunkAsync()
   at Redis.OM.Searching.RedisCollectionEnumerator`1.MoveNextAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
```

```
# redis-cli monitor
OK
1652811228.825690 [0 172.17.0.1:33076] "SELECT" "0"
1652811228.825753 [0 172.17.0.1:33076] "FT.SEARCH" "industryrecord-idx" "(@Description:\"accountant-auditor-qualified\")" "LIMIT" "0" "100"
1652811229.014780 [0 172.17.0.1:33178] "QUIT"
1652811229.014803 [0 172.17.0.1:33176] "QUIT"
```

Maybe this has to do with Indexed v.s Searchable attributes?  Are the queries mutually exclusive?  i.e. Searchable can only query .Contains() and not ==, and Indexed can only query == and not .Contains()?

**Comment by slorello89** [comment]
@VagyokC4 - So as it stands right now, redis OM only escapes those special characters in Indexed fields. Your query doesn't make a lot of sense in the context of RediSearch given that you are doing a full-text search, those special characters are going to be tokenized away at storage, so if you store:

`accountant-auditor-qualified`

all RediSearch is going to see is `accountant auditor qualified`

UNLESS you escape at the point of insertion by changing the inserted text to `accountant\-auditor\-qualified`.

Consequentially if I have an insert &  search like:

```csharp
muppets.Insert(new Muppet(){FirstName = "Bunsen", LastName = "Honeydew", PersonalStatement = "accountant\\-auditor\\-qualified"});

foreach (var muppet in muppets.Where(x => x.PersonalStatement == "accountant\\-auditor\\-qualified").ToList())
{
    Console.WriteLine(muppet.FirstName);
}
```

it will work, but if you tried to use:

```csharp
muppets.Insert(new Muppet(){FirstName = "Bunsen", LastName = "Honeydew", PersonalStatement = "accountant-auditor-qualified"});

foreach (var muppet in muppets.Where(x => x.PersonalStatement == "accountant\\-auditor\\-qualified").ToList())
{
    Console.WriteLine(muppet.FirstName);
}
```

You won't get anything back and be rather puzzled. So honestly, I think the fact that it throws these syntactical errors is actually ok, because it forces you to be a bit more intentional about your queries.

So something else that's probably worth bringing your attention to, if you are really just trying to do a faceted search here (e.g. accountant auditor and qualified are all facets you are trying to search for) `Indexed` is actually more appropriate. Because if you just would store it as `accountant|auditor|qualified`, or you changed the separator property in the IndexedAttribute to `-`, you would be able to do searches like `x.PersonalStatement == "accountant" && x.PersonalStatement=="auditor"` and actually search for the facets that interest you. This is a bit of inside baseball inside of RediSearch, which Redis OM does its best to abstract for you, but some of this syntatical stuff as you build towards more advanced usages you have to be a bit cognizant of as there's only so much the library can abstract away from you. Hopefully this helps?

See: https://redis.io/docs/stack/search/reference/escaping/ for a more in-depth explanation about tokenization in `SEARCHABLE` AKA TEXT fields.

**Comment by slorello89** [comment]
I think I've answered this question - IMO the behavior is correct here, so I'm going to go ahead and close this issue.
