### ISSUE TITLE
Update should be UpdateAsync

### ISSUE THREAD

**Issue by zulander1** [redis/redis-om-dotnet#125]
There is updateSync, and update, I think it should be reversed:

- Update (for sync)
- UpdateAsync (for async)

Thanks

**Comment by slorello89** [comment]
You're right, update can be a pretty time-consuming operation so my original intention was to force people to do it asynchronously with the sync methods added as something of an afterthought, Didn't want to change it because it's a BC to the library, fortunately still in pre 1.0 stages so I suppose we can just rev to a new minor.
