### ISSUE TITLE
Use Concurrent Dictionary Internally

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#189]
Hi @slorello89,

I came across another interesting result while testing with Redis-OM.  I think I am hitting up against internal structures when trying to do things asynchronously.

Here is my sample code:
```csharp
var categories = RedisDb.RiskCategoryRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var components = RedisDb.RiskComponentRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var factors    = RedisDb.RiskFactorRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var answers    = RedisDb.RiskAnswerRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var lookups    = RedisDb.RiskAnswerRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var overrides  = RedisDb.RiskOverrideRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();

await Task.WhenAll(categories, components, factors, answers, lookups, overrides).ConfigureAwait(false);
```

Not everytime, but when stress testing I get the following error:
```
An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Redis.OM.Searching.RedisCollectionEnumerator`1.ConcatenateRecords()
   at Redis.OM.Searching.RedisCollectionEnumerator`1.GetNextChunkAsync()
   at Redis.OM.Searching.RedisCollectionEnumerator`1.MoveNextAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
   at Redis.OM.Searching.RedisCollection`1.ToListAsync()
```

Here I am running it 20 times and you can see sometime I run without error, sometimes I get the error:

https://user-images.githubusercontent.com/253250/187561176-1a40ed92-d21b-435d-9bf0-1bdeda203b45.mp4

So I think this is happening because each call is trying to update an internal dictionary, and at times we get a race condition.  Can we can swap it from a normal dictionary to a Concurrent Dictionary that can be a little more thread safe especially during highly asynchronous use?

**Comment by slorello89** [comment]
@VagyokC4 - that's a bit odd looks like it's stripping off a level of the call stack, ConcatanteRecords doesn't call IDictionary.Add at all (the methods in the statemanager on the other-hand, do). 

You're probably right, this is probably a race, but the RedisCollection is meant to be pretty ephemeral, I don't think I've ever thought of it as thread-safe. If I had to guess I would say it's probably these two identical queries you are running:

```cs
var answers    = RedisDb.RiskAnswerRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
var lookups    = RedisDb.RiskAnswerRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
```

I'm assuming they both use the same RedisCollection you might want to change that property to initialize a new RedisColleciton rather than responding with the same one. We've spoken on the re-use of a collection in the past, which is one thing, but each of these queries is going to clear out the entire StateManager when the enumerator is initiated, so they'll inherently corrupt each others state

**Comment by VagyokC4** [comment]
@slorello89 So that brings up an interesting use case, in that I'm not even using the internal state.  In fact this operation is purely a read-only task.  Maybe it would be helpful and more optimized if I could tell Redis-OM that I want to skip the internal state management for this call?  I think I remember Entity Framework having an option like this as well via a fluent command `.AsNoTracking()`

Now that you mention it, that code sample does look a little off... here is a more complete code sample, which I've managed to control the "error" by wrapping up into a retry.   As you can see I've switched over to the ConcurrentDictionary<,> anticipating asynchronous work being done on the data.

```csharp
var retry = Policy.Handle<Exception>().WaitAndRetryAsync(new[]
{
    TimeSpan.FromMilliseconds(1),
    TimeSpan.FromMilliseconds(1),
    TimeSpan.FromMilliseconds(1),
    TimeSpan.FromMilliseconds(1),
    TimeSpan.FromMilliseconds(1)
});

await retry.ExecuteAsync(async () =>
{
    var ownerERN   = Owners[0];
    var config     = ( (RedisDb) redisDb ).RiskConfigRecord.FirstOrDefaultAsync(x => x.Owners.Contains(ownerERN));
    var categories = ( (RedisDb) redisDb ).RiskCategoryRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
    var components = ( (RedisDb) redisDb ).RiskComponentRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
    var factors    = ( (RedisDb) redisDb ).RiskFactorRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
    var answers    = ( (RedisDb) redisDb ).RiskAnswerRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();
    var industries = ( (RedisDb) redisDb ).RiskAnswerRecord.Where(x => x.Owners.Contains(ownerERN) && x.Owners.Contains(nameof (Industry))).ToListAsync();
    var countries  = ( (RedisDb) redisDb ).RiskAnswerRecord.Where(x => x.Owners.Contains(ownerERN) && x.Owners.Contains(nameof (Country))).ToListAsync();
    var products   = ( (RedisDb) redisDb ).RiskAnswerRecord.Where(x => x.Owners.Contains(ownerERN) && x.Owners.Contains(nameof (Product))).ToListAsync();
    var overrides  = ( (RedisDb) redisDb ).RiskOverrideRecord.Where(x => x.Owners.Contains(ERN)).ToListAsync();

    await Task.WhenAll(config, categories, components, factors, answers, industries, countries, products, overrides).ConfigureAwait(false);

    Categories = new ConcurrentDictionary<string, IRiskCategory>(categories.Result.ToDictionary(x => x.ERN, x => (IRiskCategory) x));
    Components = new ConcurrentDictionary<string, IRiskComponent>(components.Result.ToDictionary(x => x.ERN, x => (IRiskComponent) x));
    Factors    = new ConcurrentDictionary<string, IRiskFactor>(factors.Result.ToDictionary(x => x.ERN, x => (IRiskFactor) x));
    Answers    = new ConcurrentDictionary<string, IRiskAnswer>(answers.Result.ToDictionary(x => x.ERN, x => (IRiskAnswer) x));
    Industries = new ConcurrentDictionary<string, IRiskAnswer>(industries.Result.ToDictionary(x => x.ERN, x => (IRiskAnswer) x));
    Countries  = new ConcurrentDictionary<string, IRiskAnswer>(countries.Result.ToDictionary(x => x.ERN, x => (IRiskAnswer) x));
    Products   = new ConcurrentDictionary<string, IRiskAnswer>(products.Result.ToDictionary(x => x.ERN, x => (IRiskAnswer) x));
    Overrides  = new ConcurrentDictionary<string, IRiskOverride>(overrides.Result.ToDictionary(x => x.ERN, x => (IRiskOverride) x));
}).ConfigureAwait(false);
```

Now that those three queries are there, would you still expect a collision?  I guess this goes back to the usage of Redis-Om itself, and how it should be registered as Transient so it gets a clean one every time?  Should we think about having each collection have it's own internal state area, so that an asynchronous call like this doesn't inherently corrupt the state? 

I know at some point I will want to start using the state management features of redis-om, so it's good to get it all flushed out properly :)

**Comment by slorello89** [comment]
@VagyokC4 - see #194 - which allows you to configure your collections so they don't maintain the state - think that should resolve at least part of this.

**Comment by Jeevananthan-23** [comment]
Hi @slorello89, I have been investigating the issue of whether we can implement `ConcurrentDictionary` internally or not my answer is **no**.  https://github.com/redis/redis-om-dotnet/blob/71c21738a357792fb18ecbcee7b5a002f3576f25/test/Redis.OM.Unit.Tests/RediSearchTests/BulkOperationsTests.cs#L224

The above test is a pretty good example of the same issue `FindByIdsAsync( IEnumerable<string> ids)` method which calls asyncly. Which hits the internal `SaveToStateManager` first which is a bad idea because the state has non-persisted data and has concurrency issues while having conflict with the `InsertAsync(IEnumerable<T> items)` method with the same `IDs/Keys`. 


And I feel that the current implementation of `FindByIdAsyncNoSave(string id)` is good because we don't hit the `SaveToStateManager` at first which is having **Non-Persisted Data**. So we don't need this change using `ConcurrentDictionary` internally in `SaveToStateManager`.

**Comment by slorello89** [comment]
I agree with you @Jeevananthan-23 - I don't think a concurrent dictionary is appropriate to use here, as any use of it would just hide very real race-conditions that we should just let naturally bubble up, the PRs that have come out of this have done just that with some more helpful messaging than we had before.

@VagyokC4 - thinking about the API you proposed here: `.AsNoTracking()` - IMO the stateless collection is so light weight that I don't know that there's a meaningful gain to be made from implementing it, so I'm going to go ahead and close this issue to tidy up :)
