### ISSUE TITLE
Redis.OM.Analyzer commands file path

### ISSUE THREAD

**Issue by zhiburt** [redis/redis-om-dotnet#20]
Hi @slorello89

I am not an expert in .NET and C# but seems to me this must be a relative path ?:)

https://github.com/redis/redis-om-dotnet/blob/2b26041d1ceccf1326dc95b5f92b36d8b6cbb57d/src/Redis.OM.Analyzer/RedisCommandsAnalyzer.cs#L28

Might something like `Environment.CurrentDirectory` or `AppDomain.CurrentDomain.BaseDirectory` be used.

**Comment by slorello89** [comment]
Hi @zhiburt Thanks for opening this issue - yep that definitely shouldn't be in there, fortunately, it's not shipped as part of Redis.OM (it's more like a POC stuff of Redis.OM) - It might need a slightly different way to access the path because it's a code analyzer not certain, will look when I get back.

**Comment by slorello89** [comment]
going to close this out as it really doesn't do anything - probably should just delete the old POC stuff at some point.
