### ISSUE TITLE
Get entity from IRedisCollection with private fields

### ISSUE THREAD

**Issue by giovanni-ferrari** [redis/redis-om-dotnet#287]
In the following example the "Product" entity, is correctly stored in Redis, including the values of the "Tags" property, but when getting the entity from the IRedisCollection the "Tags" property is not valorized correctly.

    public class Product
    {
        private List<string> _tags = new List<string>();

        public IEnumerable<string> Tags => _tags;

        [RedisIdField][Indexed] 
        public string Id { get; set; }

        public void AddTag(string tag)
        {
            _tags.Add(tag);
        }
    }

Is it possible to add backing field management feature?

**Comment by VagyokC4** [comment]
I think your problem is that the `Tags => _tags;` ends up being a Getter only.  There is no setter available to re-insert the values, and it's not going to call `AddTag(string tag)`

You will have to allow the serializer a way to re-populate that value.

If this was a true backing field with both a `get;` and `set;` then it would work fine (I think).

**Comment by giovanni-ferrari** [comment]
> I think your problem is that the `Tags => _tags;` ends up being a Getter only. There is no setter available to re-insert the values, and it's not going to call `AddTag(string tag)`
> 
> You will have to allow the serializer a way to re-populate that property, otherwise you get what you are seeing.
> 
> If this was a true backing field with both a `get;` and `set;` then it would work fine (I think).

Yes, exactly. But my intention is to not allow the users of the class to directly modify the collection. 
EF for example handles this correctly https://learn.microsoft.com/en-us/ef/core/modeling/backing-field?tabs=data-annotations#field-only-properties

**Comment by slorello89** [comment]
@giovanni-ferrari - this is a question of seralizers - for our part we use System.Text.Json to handle the JSON backed types, so if you wanted to handle something comparable to this (have a private setter) you could do so if you use the `JsonIncludeAttribute` to decorate the `Tags` property - and gave it a private setter rather than having the  


```cs
    [Document(StorageType = StorageType.Json)]
    public class Product
    {
        [JsonInclude]
        public IList<string> Tags { get; private set; } = new List<string>();

        [RedisIdField][Indexed] 
        public string Id { get; set; }


        public void AddTag(string tag)
        {
            Tags.Add(tag);
        }
    }

```

**Comment by slorello89** [comment]
Closing to tidy up.
