### ISSUE TITLE
AWS Memory DB for Redis | Index create issue

### ISSUE THREAD

**Issue by srivathsa0205** [redis/redis-om-dotnet#427]
i am using MeomryDb for Redis from AWS and trying to create index for my DB but i am getting an error as "SYNTAXERR JSON path must start with '$'. Invalid path: SORTABLE" 

this is the command FT.CREATE position-idx ON Json PREFIX 1 RedisPostions SCHEMA $.RedisKey AS RedisKey TAG SEPARATOR | $.PositionId AS PositionId NUMERIC $.BranchCode AS BranchCode TAG SEPARATOR | $.ClientAccountCode AS ClientAccountCode TAG SEPARATOR | $.PositionType AS PositionType TAG SEPARATOR | $.UserId AS UserId TAG SEPARATOR | $.ClientUserId AS ClientUserId TAG SEPARATOR | $.PositionQuantity AS PositionQuantity NUMERIC **SORTABLE **| $.QuantityElected AS QuantityElected NUMERIC $.QuantityUnElected AS QuantityUnElected NUMERIC $.QuantityOverElected AS QuantityOverElected NUMERIC $.PositionTimestamp AS PositionTimestamp NUMERIC $.AccountShortName AS AccountShortName TAG SEPARATOR |

<img width="309" alt="image" src="https://github.com/redis/redis-om-dotnet/assets/153760934/6c7e9189-2c78-4eb5-8ccf-efa9ba091685">

**Comment by slorello89** [comment]
Hi @srivathsa0205 - Redis OM is a Redis query & search client, so really all I can offer by way of supporting this is to tell you to switch to using Search and Query (using Redis Enterprise(which is available in the AWS marketplace), Redis Cloud, or running your own Redis Stack instances). 

MemoryDB's new search capabilities are an attempt to replicate the Redis' search and query API, they can't actually use the same software (because of licensing) so compatibility issues like this are inevitable.

FWIW, you might be able to remove `Sortable=true`. I don't know what that means for sortability, in Search and Query we use `Sortable` to instruct Redis to construct the index to optimize sorts for speed (at the cost of memory) - without it you can still sort (it's just slower). Not sure how MemoryDB works, I'd look into it but unlike RediSearch, they're closed source. So I won't speculate further.

**Comment by srivathsa0205** [comment]
@slorello89 thank you! for the response.
