### ISSUE TITLE
No Status is returned by many commands 

### ISSUE THREAD

**Issue by reza-esfandyari** [redis/redis-om-dotnet#433]
Hello, 

Could you please take a look and see if this is legit or if I need to do things differently?

Here is an example of my code: 

        ` string status =  await _redisConnectionProvider.Connection.UnlinkAsync($"student:{studentId}");`

Under the hood in namespace Redis.OM --> public static class RedisCommands

`   
    public static string Unlink(this IRedisConnection connection, string key) => (string) connection.Execute("UNLINK", (object) key);`

Status is always empty string --> ""

OR: I tried to go deeper and I found this result: 

        ` var status= await _redisConnectionProvider.Connection.ExecuteAsync("UNLINK",$"student:{studentId}");`

here status is of type `Task<RedisReply>` and return _internalLong which can be used to check the status but I felt it is not very straightforward

**Comment by slorello89** [comment]
Unlink wouldn't return a 'status' per se, it would return the number of keys that the unlink touched. Not entirely sure why this was set to a string (that's why it's not working)

 ```cs
var numUnlinked = (long)(await _redisConnectionProvider.Connection.ExecuteAsync("UNLINK",$"student:{studentId}"));
```

Will get the result you're looking for (we'll need to change this API so it's correct). Interesting that this hasn't come up before.

**Comment by reza-esfandyari** [comment]
@slorello89, thanks very much for your quick response and also for your videos on YouTube, very insightful :)
