### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by delepster** [redis/redis-om-dotnet#449]
I get an exception when using `Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync`:

```
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Redis.OM.Searching.RedisCollection`1.SaveToStateManager(String key, Object value)
   at Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync(Expression`1 expression)
```

It seems to involve some dictionary used within the implementation. I am not sure how I can solve this. A bit more information about my use case:

- sentinel mode
- ~30 keys
- entry is a hashset of 9 properties, weighing 456B
- the expression filters on an indexed field (obviously)

**Comment by delepster** [comment]
Are the queries threadsafe?

**Comment by slorello89** [comment]
Queries within the `RedisCollection` are only thread-safe if `saveState` is set to false, otherwise the collection tracks every individual record added it and cleares the entire cache of records each time the collection is materialized. If `saveState` is set to false, then it's a non issue. You can set `saveState` to false when you initialize the collection (either with the provider or if you new it up)

**Comment by slorello89** [comment]
This has come up a few times so I added it to the FAQ - probably closes this out.

**Comment by delepster** [comment]
Thanks for the info, I'll close this issue and try this.
