### ISSUE TITLE
Pass existing IConnectionMultiplexer object into RedisConnectionProvider constructor

### ISSUE THREAD

**Issue by yorfmeister69** [redis/redis-om-dotnet#54]
How about we pass an existing IConnectionMultiplexer connection to the RedisConnectionProvider 's constructor? Most of the times, we already have a IConnectionMultiplexer object already injected to our DI. So injecting a new RedisConnectionProvider to our DI, just creates 2 instances of the IConnectionMultiplexer object since the RedisConnectionProvider internally created another IConnectionMultiplexer object.

**Comment by yorfmeister69** [comment]
Any updates on this? Should I create a PR for this?

**Comment by slorello89** [comment]
It's something I was initially skeptical about (essentially exposing another library's classes through Redis OM) but you have a solid point, there's no way to use a pre-existing Multiplexer in Redis OM .NET at the moment, which is not ideal for StackExchange.Redis. Fortunately, looks like your cause was picked up by #59, so it should be in there pretty soon.

**Comment by slorello89** [comment]
Resolved in v0.1.7, so I'm closing this issue.
